Repository perArdua/CapstoneDesign, pull requests merged in 2023-05, with the labels that each got.

#33 Feature/ccp 16 social login UI
  CampusIn.xcodeproj/project.pbxproj
  CampusIn.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  CampusIn.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  CampusIn.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  CampusIn.xcodeproj/xcuserdata/idonghyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  CampusIn/AppDelegate.swift
  CampusIn/Assets.xcassets/AccentColor.colorset/Contents.json
  CampusIn/Assets.xcassets/AppIcon.appiconset/Contents.json
  CampusIn/Assets.xcassets/Contents.json
  CampusIn/Base.lproj/LaunchScreen.storyboard
  CampusIn/Base.lproj/Main.storyboard
  CampusIn/Info.plist
  CampusIn/SceneDelegate.swift
  CampusIn/ViewController.swift
  CampusIn/Views/Main.storyboard
  CampusInTests/CampusInTests.swift
  CampusInUITests/CampusInUITests.swift
  CampusInUITests/CampusInUITestsLaunchTests.swift
Labels: enhancement

#35 Feature/ccp 17 general posting UI
  CampusIn.xcodeproj/project.pbxproj
  CampusIn.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  CampusIn/Controllers/ViewController.swift
  CampusIn/Models/temp.swift
  CampusIn/Views/Posting/GeneralPostingViewController.storyboard
Labels: enhancement

#37 xcuserstate 트래킹 해제
  .gitignore
  CampusIn.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
Labels: invalid

#38 Revert "xcuserstate 트래킹 해제"
  .gitignore
  CampusIn.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
Labels: invalid

#46 Feature/ccp 24 exclude xcuserdata
  CampusIn.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Labels: enhancement

#47 Feature/cpp 18 google login
  CampusIn.xcodeproj/project.pbxproj
  CampusIn/Assets.xcassets/CampusIn_logo.imageset/CampusIn_logo.png
  CampusIn/Assets.xcassets/CampusIn_logo.imageset/Contents.json
  CampusIn/Controllers/LoginViewController.swift
  CampusIn/Controllers/SocialViewController.swift
  CampusIn/Controllers/ViewController.swift
  CampusIn/Views/Main.storyboard
Labels: enhancement

#48 자유게시판 목록 구현
  CampusIn.xcodeproj/project.pbxproj
  CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  CampusIn/Models/Datas/GeneralPosting/GeneralPostingContent.swift
  CampusIn/Models/Datas/GeneralPosting/PostingManager.swift
  CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingCommentTableViewCell.swift
  CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingContentTableViewCell.swift
  CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingTableViewCell.swift
Labels: enhancement

#51 Feature/cpp 25 key chain token storing
  CampusIn/Models/KeyChain.swift
Labels: enhancement

#52 Feat. 자유게시판 글 작성 로직 구현
  CampusIn.xcodeproj/project.pbxproj
  CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingAddViewController.swift
Labels: enhancement

#54 Feature/ccp 26 nickname
  CampusIn.xcodeproj/project.pbxproj
  CampusIn.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  CampusIn/Controllers/NickNameViewController.swift
  CampusIn/Views/NickNameViewController.storyboard
Labels: enhancement

#56 Feature/ccp 27 identify login
  CampusIn/AppDelegate.swift
Labels: enhancement

#57 Feat. 자유게시판 검색 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingSearchViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Views/Main.storyboard
  FrontEnd/CampusIn/Views/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralSearchTableViewCell.swift
  FrontEnd/Pods/Pods.xcodeproj/project.pbxproj
Labels: enhancement

#62 Feat. 자유게시판 글 작성 버튼 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
Labels: bug

#73 Feature/ccp 28 write general post
  .DS_Store
  FrontEnd/.DS_Store
  FrontEnd/CampusIn.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
  FrontEnd/CampusIn.xcworkspace/xcuserdata/choidagyeong.xcuserdatad/UserInterfaceState.xcuserstate
  FrontEnd/CampusIn/Assets.xcassets/1.imageset/1.png
  FrontEnd/CampusIn/Assets.xcassets/1.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/10.imageset/10.png
  FrontEnd/CampusIn/Assets.xcassets/10.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/11.imageset/11.png
  FrontEnd/CampusIn/Assets.xcassets/11.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/12.imageset/12.png
  FrontEnd/CampusIn/Assets.xcassets/12.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/13.imageset/13.png
  FrontEnd/CampusIn/Assets.xcassets/13.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/14.imageset/14.png
  FrontEnd/CampusIn/Assets.xcassets/14.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/15.imageset/15.png
  FrontEnd/CampusIn/Assets.xcassets/15.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/16.imageset/16.png
  FrontEnd/CampusIn/Assets.xcassets/16.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/17.imageset/17.png
  FrontEnd/CampusIn/Assets.xcassets/17.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/18.imageset/18.png
  FrontEnd/CampusIn/Assets.xcassets/18.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/19.imageset/19.png
  FrontEnd/CampusIn/Assets.xcassets/19.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/2.imageset/2.png
  FrontEnd/CampusIn/Assets.xcassets/2.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/3.imageset/3.png
  FrontEnd/CampusIn/Assets.xcassets/3.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/4.imageset/4.png
  FrontEnd/CampusIn/Assets.xcassets/4.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/5.imageset/5.png
  FrontEnd/CampusIn/Assets.xcassets/5.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/6.imageset/6.png
  FrontEnd/CampusIn/Assets.xcassets/6.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/7.imageset/7.png
  FrontEnd/CampusIn/Assets.xcassets/7.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/8.imageset/8.png
  FrontEnd/CampusIn/Assets.xcassets/8.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/9.imageset/9.png
  FrontEnd/CampusIn/Assets.xcassets/9.imageset/Contents.json
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingAddViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/GeneralPosting/PostingManager.swift
  FrontEnd/CampusIn/Views/Posting/GeneralPostingViewController.storyboard
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
  gitignore
Labels: enhancement

#95 Feature/ccp 43 message repository
  BackEnd/campusin/src/main/java/com/example/campusin/infra/message/MessageRepository.java
  BackEnd/campusin/src/main/java/com/example/campusin/infra/message/MessageRoomRepository.java
Labels: enhancement

#93 Feature/ccp 41 message controller
  BackEnd/campusin/src/main/java/com/example/campusin/api/message/MessageController.java
  BackEnd/campusin/src/main/java/com/example/campusin/api/message/MessageRoomController.java
Labels: enhancement

#92 Feature/ccp 39 message entities
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/Message.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/MessageRoom.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/VisibilityState.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/MessageRoomsWithLastMessages.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/request/MessageRoomCreateRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/request/MessageRoomGetRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/request/MessageSendRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/response/MessageResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/response/MessageRoomIdResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/response/MessageRoomListResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/message/dto/response/MessageRoomResponse.java
Labels: enhancement

#116 Feat. Todo list UI 구현
  FrontEnd/CampusIn/Views/Study/TodoListCell.swift
  FrontEnd/CampusIn/Views/StudyManage.storyboard
  FrontEnd/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-CampusIn.xcscheme
Labels: enhancement

#127 Feature/ccp fix tab bar UI
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Controllers/MessageBoxViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
Labels: bug

#154 Feat. 쪽지 전송 로직 구현
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Models/ChatMessage.swift
  FrontEnd/CampusIn/Views/TableViewCells/ChatTableViewCell.swift
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: enhancement

#155 Feat. api data model 정의
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/APIConstants.swift
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: enhancement

#156 Feat. 자유게시판 검색 api 연결
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingAddViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingSearchViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/GeneralPostingContent.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/GeneralPostingMain.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostingManager.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostingSearch.swift
Labels: enhancement

#159 Feat. 자유게시판 api 요청 로직 수정
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingAddViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingSearchViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/ChatMessage.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostList.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostSearch.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostingManager.swift
  FrontEnd/CampusIn/Models/Datas/Response.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
Labels: fix

#161 Feat. 로그인 UI 개선
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Assets.xcassets/googleLogin.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/googleLogin.imageset/btn_google_light_normal_ios.png
  FrontEnd/CampusIn/Assets.xcassets/googleLogin2.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/googleLogin2.imageset/btn_google_signin_light_normal_ios.png
  FrontEnd/CampusIn/Assets.xcassets/googleLogin3.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/googleLogin3.imageset/googleLogin3.png
  FrontEnd/CampusIn/Assets.xcassets/kakaoLogin.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/kakaoLogin.imageset/kakao_login_medium_narrow.png
  FrontEnd/CampusIn/Controllers/LoginViewController.swift
  FrontEnd/CampusIn/Controllers/SideMenuViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Views/Main.storyboard
Labels: enhancement

#167 Feat. Pageable 관련 수정
  BackEnd/campusin/src/main/java/com/example/campusin/common/config/swagger/SwaggerConfig.java
Labels: fix

#168 Feature/ccp 64 todolist entity
  BackEnd/campusin/src/main/java/com/example/campusin/domain/todo/Todo.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/todo/dto/request/TodoRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/todo/dto/request/TodoUpdateRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/todo/dto/response/TodoIdResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/todo/dto/response/TodoResponse.java
Labels: enhancement

#169 Feat. Todo Controller 작성
  BackEnd/campusin/src/main/java/com/example/campusin/api/todo/TodoController.java
Labels: enhancement

#170 Feat. Todo Repository 작성
  BackEnd/campusin/src/main/java/com/example/campusin/infra/todo/TodoRepository.java
Labels: enhancement

#171 Feat. Todo Service 작성
  BackEnd/campusin/src/main/java/com/example/campusin/application/todo/TodoService.java
Labels: enhancement

#173 Feat. 로그아웃 로직 구현
  FrontEnd/CampusIn/Controllers/NickNameViewController.swift
  FrontEnd/CampusIn/Controllers/SideMenuViewController.swift
Labels: enhancement

#185 Feature/ccp 90 modify comment
  BackEnd/campusin/src/main/java/com/example/campusin/api/comment/CommentController.java
  BackEnd/campusin/src/main/java/com/example/campusin/application/comment/CommentService.java
  BackEnd/campusin/src/main/java/com/example/campusin/common/config/swagger/SwaggerConfig.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/dto/request/CommentCreateRequest.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/dto/response/CommentCreateResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/dto/response/CommentOneResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/dto/response/CommentResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/dto/response/CommentsOnPostResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/request/CommentCreateDto.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/response/CommentCreateResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/response/CommentResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/infra/comment/CommentRepository.java
  BackEnd/campusin/src/main/java/com/example/campusin/infra/comment/CommentRepositoryCustom.java
  BackEnd/campusin/src/main/java/com/example/campusin/infra/comment/CommentRepositoryImpl.java
Labels: enhancement

#187 Feat. Todo Api reference
  BackEnd/campusin/src/main/java/com/example/campusin/api/todo/TodoController.java
Labels: enhancement

#196 Feature/ccp 88 timer
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MessageBoxViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyManageViewController.swift
  FrontEnd/CampusIn/Controllers/StudyManageViewController.swift
  FrontEnd/CampusIn/Models/Datas/Study/TimerData.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Models/Study/TimerManager.swift
  FrontEnd/CampusIn/Models/Study/TimerTableViewCellDelegate.swift
  FrontEnd/CampusIn/Views/Buttons.swift
  FrontEnd/CampusIn/Views/StudyManageViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/Study/TimerCollectionViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/Study/TimerTableViewCell.swift
Labels: enhancement

#197 Feat. 쪽지 전송data model 정의 및 api 연결
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Controllers/MessageBoxViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/ChatMessage.swift
  FrontEnd/CampusIn/Models/Datas/Chats.swift
  FrontEnd/CampusIn/Models/Datas/MessageRooms.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/MessageManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/MessageRoomManager.swift
  FrontEnd/CampusIn/Views/TableViewCells/ChatTableViewCell.swift
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: enhancement

#198 Feat. 파싱 로직 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/BoardData.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostList.swift
  FrontEnd/CampusIn/Models/Datas/Response.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
Labels: enhancement, fix

#205 Feature/ccp 97 revert file
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MessageBoxViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/MessageManager.swift
Labels: fix

#206 Feat .자유게시판 게시글 상세 수정
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/CommetData.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostDetail.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
Labels: fix

#208 Feat. 쪽지 전송 로직 수정
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/MessageManager.swift
  FrontEnd/CampusIn/Views/TableViewCells/ChatTableViewCell.swift
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: fix

#210 Feat. 닉네임 설정 및 기존 회원 구분 로직 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/NickNameViewController.swift
  FrontEnd/CampusIn/Controllers/SideMenuViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/Chatting/Chats.swift
  FrontEnd/CampusIn/Models/Datas/Chatting/MessageRooms.swift
  FrontEnd/CampusIn/Models/Datas/Users/UserData.swift
  FrontEnd/CampusIn/Models/Datas/Users/UserNickname.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/UserManager.swift
Labels: enhancement

#212 Feat. 메세지 버그 수정
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Controllers/MessageBoxViewController.swift
Labels: fix

#216 Feat. TodoList UI 및 로직 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/ChatViewController.swift
  FrontEnd/CampusIn/Controllers/NickNameViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyManageViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyNavigationController.swift
  FrontEnd/CampusIn/Controllers/Study/ToDoViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/ToDoList/TodoCreationResponse.swift
  FrontEnd/CampusIn/Models/Datas/ToDoList/TodoList.swift
  FrontEnd/CampusIn/Models/Datas/Users/UserNickname.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/TodoManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/UserManager.swift
  FrontEnd/CampusIn/Views/Main.storyboard
  FrontEnd/CampusIn/Views/StudyNavigationController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/Study/ToDoTableViewCell.swift
  FrontEnd/Pods/Pods.xcodeproj/xcuserdata/choidagyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: enhancement

#217 Feat. 게시글 수정 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingAddViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/BoardInitResponse.swift
  FrontEnd/CampusIn/Models/Datas/Response.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Views/Posting/GeneralPostingViewController.storyboard
Labels: enhancement

#228 Feat. StudyGroup Controller 작성
  BackEnd/campusin/src/main/java/com/example/campusin/api/studygroup/StudyGroupController.java
Labels: enhancement
