Repository perArdua/CapstoneDesign, pull requests merged in 2023-09, with the labels that each got.

#408 Feature/ccp 200 modify rankand study group member time
  BackEnd/campusin/src/main/java/com/example/campusin/api/post/PostController.java
  BackEnd/campusin/src/main/java/com/example/campusin/api/rank/RankController.java
  BackEnd/campusin/src/main/java/com/example/campusin/api/studygroup/StudyGroupController.java
  BackEnd/campusin/src/main/java/com/example/campusin/application/rank/RankService.java
  BackEnd/campusin/src/main/java/com/example/campusin/application/studygroup/StudyGroupService.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/rank/Rank.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/rank/dto/response/RankListQuestResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/rank/dto/response/RankListResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/studygroup/dto/response/StudyGroupTimeResponse.java
  BackEnd/campusin/src/main/java/com/example/campusin/infra/rank/RankRepository.java
Labels: fix

#410 패치노트 1.0.7
  백엔드 패치노트.txt
Labels: documentation

#413 Feat. 내가 쓴 게시글 보기 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/BookStore/BookStoreViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/MyPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingViewController.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
Labels: enhancement

#424 [CCP-202] feat. 개인관련 랭킹 api 연결
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Ranking/RankingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Ranking/PersonalStudyRankingData.swift
  FrontEnd/CampusIn/Models/Datas/Ranking/RankingData.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/RankingManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/StatisticsManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/RankingViewController.storyboard
Labels: enhancement

#432 [CCP-209] fix. 각 게시판 게시글 상세 구성 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostDetail.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostList.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/QuestionPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/StudyPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingTableViewCell.swift
Labels: fix

#433 [CCP-214] fix. 스터디 그룹 모집 게시글 작성이 안되는오류 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingAddViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/TagData.swift
Labels: bug, fix

#434 [CCP-208] feat. 그룹원들 타이머 표시
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Study/StudyManageViewController.swift
  FrontEnd/CampusIn/Models/Datas/Study/GroupTimerResponse.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/StudyGroupManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/StudyNavigationController.storyboard
Labels: enhancement

#435 Feat. study record CRUD
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Study/StudyManageViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyAddRecordViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyDetailRecordViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyRecordViewController.swift
  FrontEnd/CampusIn/Models/Datas/Study/StudyRecordResponse.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/StudyRecordManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/StudyNavigationController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/Study/StudyRecordTableViewCell.swift
Labels: enhancement

#442 Feat. Like 수정
  BackEnd/campusin/src/main/java/com/example/campusin/application/comment/CommentLikeService.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/.DS_Store
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/Comment.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/comment/CommentLike.java
  BackEnd/campusin/src/main/java/com/example/campusin/domain/post/PostLike.java
Labels: fix

#446 Feature/ccp 220 modify like
  BackEnd/campusin/src/main/java/com/example/campusin/api/comment/CommentLikeController.java
  BackEnd/campusin/src/main/java/com/example/campusin/api/post/PostController.java
  BackEnd/campusin/src/main/java/com/example/campusin/application/comment/CommentLikeService.java
  BackEnd/campusin/src/main/java/com/example/campusin/application/post/PostService.java
Labels: fix

#449 Feat. 자유게시판 좋아요 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostLikeResponse.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingContentTableViewCell.swift
Labels: enhancement

#452 Feat. 스터디 그룹 모집 게시판 좋아요 기능 삭제
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/StudyPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingTableViewCell.swift
Labels: enhancement

#453 [CCP-217] feat. 현재 주차 그룹 랭킹 확인 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Ranking/RankingViewController.swift
  FrontEnd/CampusIn/Models/Datas/Ranking/StudyGroupRankingCreateData.swift
  FrontEnd/CampusIn/Models/Datas/Ranking/StudyGroupRankingData.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/RankingManager.swift
Labels: enhancement

#457 Feat. 질의응답 게시글 좋아요 기능 구현
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/QuestionPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingContentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingTableViewCell.swift
Labels: enhancement

#458 Feat. Todo navigation controller 수정
  FrontEnd/CampusIn/Controllers/Study/ToDoViewController.swift
Labels: fix

#459 [CCP-212] fix. 댓글 작성시 UI가 즉시 업데이트 되도록 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Network/Manager/CommentManager.swift
Labels: fix

#477 Feat. 관리자 페이지 UI 작성
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ManagerViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/ReportedCommentViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/ReportedPostViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/UserBadgeViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/SideMenuViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/MyPage/ReportedCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/MyPage/ReportedPostTableViewCell.swift
Labels: enhancement

#484 Feature/ccp 239 posting badge
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ReportedCommentViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Badge/BadgeData.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostDetail.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostList.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostSearch.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BadgeManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/QuestionPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/StudyPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingContentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/AdoptCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingContentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingContentTableViewCell.swift
Labels: enhancement

#485 [CCP-224] feat. 특정 주차 그룹 랭킹 조회 기능 추가
  FrontEnd/CampusIn/Controllers/Ranking/RankingViewController.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/RankingManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/StatisticsManager.swift
Labels: enhancement

#488 Feat. 댓글신고, 블락, 언블락 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ReportedCommentViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Admin/BlockCommentData.swift
  FrontEnd/CampusIn/Models/Datas/Admin/ReportedCommentData.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/CommetData.swift
  FrontEnd/CampusIn/Models/Delegates/ReplyLikeBtn.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/AdminManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/QuestionPostingViewController.storyboard
  FrontEnd/CampusIn/Views/StroryBoards/Posting/StudyPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/MyPage/ReportedCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/ReplyCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingCommentTableViewCell.swift
Labels: enhancement

#487 [CCP-240] fix. 댓글 답글 작성 안되는 오류 수정
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Ranking/RankingViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyRecordAddViewController.swift
  FrontEnd/CampusIn/Models/Delegates/UpdateReplyDelegate.swift
Labels: bug, fix

#492 [CCP-242] feat. 랭킹 오류 수정
  FrontEnd/CampusIn/Controllers/Ranking/RankingViewController.swift
  FrontEnd/CampusIn/Models/Network/Manager/RankingManager.swift
Labels: bug, fix

#496 Feat. 게시글 블락 및 언블락 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ReportedPostViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Admin/BlockPostData.swift
  FrontEnd/CampusIn/Models/Datas/Admin/ReportedPostData.swift
  FrontEnd/CampusIn/Models/Network/Manager/AdminManager.swift
Labels: enhancement

#498 [CCP-244] feat. 사용자 뱃지 신청 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/MyPageViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Models/Datas/Users/UserIDData.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
  FrontEnd/CampusIn/Models/Network/Manager/UserManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
Labels: enhancement

#500 Feat. 댓글 좋아요 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/CommentLikeResponse.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/CommetData.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/CommentManager.swift
  FrontEnd/CampusIn/Views/TableViewCells/GeneralPosting/GeneralPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/QuestionPosting/QuestionPostingCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/ReplyCommentTableViewCell.swift
  FrontEnd/CampusIn/Views/TableViewCells/StudyPosting/StudyPostingCommentTableViewCell.swift
Labels: enhancement

#503 Feat. 일반 사용자 게시글 신고 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ReportedPostViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/PostSingoResponse.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
Labels: enhancement

#504 Feat. 사용자 댓글 신고 기능 구현
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/MyPage/ReportedCommentViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/ReportedPostViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Models/Datas/Posting/GeneralPosting/CommentSingoResponse.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/CommentManager.swift
Labels: enhancement

#506 [CCP-245] feat. 관리자 뱃지 관리 기능 추가
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Controllers/Badge/BadgeDatailViewController.swift
  FrontEnd/CampusIn/Controllers/Badge/BadgeListViewController.swift
  FrontEnd/CampusIn/Controllers/MyPage/MyPageViewController.swift
  FrontEnd/CampusIn/Models/Datas/Admin/HandleBadgeData.swift
  FrontEnd/CampusIn/Models/Datas/Admin/MakeBadgeData.swift
  FrontEnd/CampusIn/Models/Network/APIConstants.swift
  FrontEnd/CampusIn/Models/Network/Manager/AdminManager.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/BadgeTableViewCell.swift
Labels: enhancement

#507 [CCP-243] fix. 질의 응답 게시판 태그 수정
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingAddViewController.swift
Labels: fix

#508 Feat. 뱃지 오류 수정
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/PostingReplyViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/Posting/GeneralPostingViewController.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/ReplyCommentTableViewCell.swift
Labels: enhancement

#511 [CCP-251] fix. 스터디 그룹 기록 게시글 기본 이미지 추가
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyDetailRecordViewController.swift
  FrontEnd/CampusIn/Controllers/Study/StudyRecord/StudyRecordViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/StudyNavigationController.storyboard
Labels: fix

#513 Feat. 투두 navigation controller 수정
  FrontEnd/CampusIn/Controllers/Study/ToDoViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
Labels: fix

#515 [CCP-253] Feat.관리자만 관리자 페이지 볼 수 있도록 구현
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/SideMenuViewController.swift
  FrontEnd/CampusIn/Models/Datas/Admin/HandleBadgeData 2.swift
  FrontEnd/CampusIn/Models/Datas/Admin/MakeBadgeData 2.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
  FrontEnd/CampusIn/Views/TableViewCells/BadgeTableViewCell 2.swift
Labels: enhancement

#563 Feat. 로그인 로직 수정
  FrontEnd/CampusIn/Controllers/LoginViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Info.plist
Labels: enhancement

#567 Feat. 로그인 로직 수정
  FrontEnd/CampusIn/Controllers/LoginViewController.swift
  FrontEnd/CampusIn/Controllers/SocialViewController.swift
  FrontEnd/CampusIn/Info.plist
Labels: enhancement

#575 Feature/ccp 284 naver login
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn/Assets.xcassets/naverLogin.imageset/Contents.json
  FrontEnd/CampusIn/Assets.xcassets/naverLogin.imageset/naverLogin.png
  FrontEnd/CampusIn/CampusIn++Bundle.swift
  FrontEnd/CampusIn/Controllers/LoginViewController.swift
  FrontEnd/CampusIn/Controllers/ViewController.swift
  FrontEnd/CampusIn/Views/StroryBoards/Main.storyboard
Labels: enhancement

#579 Feat. 책방 리프레시 수정 및 버그 수정
  FrontEnd/CampusIn.xcodeproj/project.pbxproj
  FrontEnd/CampusIn.xcworkspace/xcuserdata/choedagyeong.xcuserdatad/UserInterfaceState.xcuserstate
  FrontEnd/CampusIn/Controllers/BookStore/BookStoreViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/GeneralPosting/GeneralPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/QuestionPosting/QuestionPostingViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingDetailViewController.swift
  FrontEnd/CampusIn/Controllers/Posting/StudyPosting/StudyPostingViewController.swift
  FrontEnd/CampusIn/Models/Network/Manager/BoardManager.swift
Labels: fix
